### ISSUE TITLE
Change the ellipsis outline characters

### ISSUE THREAD

**Issue by mrbig033** [rnkn/fountain-mode#100]
Can I make the three dots become one?

**Comment by rnkn** [comment]
If this is possible it will be in the `outline` customization group. Fountain Mode just uses Outline to collapse sections.

**Comment by mrbig033** [comment]
Thanks! [This did the trick](https://www.emacswiki.org/emacs/OutlineMode#toc3):

```
 (set-display-table-slot standard-display-table 
                         'selective-display 
                         (string-to-vector "More..."))
```
