### ISSUE TITLE
What is the best/recommended way to export to PDF?

### ISSUE THREAD

**Issue by mrbig033** [rnkn/fountain-mode#101]
I understand this package do not export directly to PDF, so how should I proceed to accomplish this while preserving formatting at the same time?

**Comment by rnkn** [comment]
You can export Fountain -> LaTeX -> PDF, but a better way to convert Fountain -> PDF is to install afterwriting package via npm. Then use `fountain-export-shell-command` (which is setup to use afterwriting by default).

**Comment by mrbig033** [comment]
I'm sorry, I could not find this menu entry, but there is a `Fountain -> Export -> Buffer to Latex`. Is this the one you have in mind?

**Comment by mrbig033** [comment]
Okay then, I'll try this package. I was trying to avoid installing npm on my system, it wasn't very easy last time. Thanks ;)

**Comment by mrbig033** [comment]
Afterwriting works great! Since this is a package targeting non-programmers, may I suggest adding some brief, laymen friendly instructions on how to install and use this package?

**Comment by mrbig033** [comment]
I understand. I started drafting something in the direction I proposed. Should I make a pull request, or send it to the mailing list? I never used those, to be hones.

**Comment by rnkn** [comment]
Everything really should go to the GNU ELPA repo. PR's here will not be reflected within Emacs.
