### ISSUE TITLE
`fountain-tab-action` keeps working outside the fountain buffer

### ISSUE THREAD

**Issue by mrbig033** [rnkn/fountain-mode#102]
#### Runtime Environment

- MX Linux 17
- GNU Emacs 27.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.22.11) of 2018-11-28
- Evil version 1.2.13
- [.emacs.d](https://github.com/mrbig033/dotfiles/tree/master/emacs/emacs_default)
- [packages](https://github.com/mrbig033/dotfiles/blob/master/emacs/emacs_default/packs.el)
- fountain-mode-20181011.843

#### Issue

After using Fountain Mode, `TAB` has `fountain-tab-action` as a result. I was able to reproduce it on Org Mode and Markdown Mode. It only happens consistently with Evil Mode activated (toggled with `M-x evil-mode`). It does not happen if I run `evil-emacs-state` interactively.

##### Fountain use-package declaration

``` emacs-lisp
(use-package fountain-mode
:defer t
:ensure t
:init
(add-hook 'fountain-mode-hook 'outline-minor-mode)
(add-hook 'fountain-mode-hook 'imenu-list-minor-mode)
(set-display-table-slot standard-display-table
                        'selective-display
                        (string-to-vector "."))
:config

(general-define-key
:keymaps 'fountain-mode-map
"M-," 'fountain-backward-scene
"M-." 'fountain-forward-scene
"C-M-," 'fountain-outline-previous
"C-M-." 'fountain-outline-next)

(general-nvmap
:keymaps 'fountain-mode-map
"M-," 'fountain-backward-scene
"M-." 'fountain-forward-scene
"C-M-," 'fountain-outline-previous
"C-M-." 'fountain-outline-next)

(general-nvmap
"RET" 'imenu
"gh" 'fountain-outline-up
"]" 'fountain-outline-next
"TAB" 'fountain-tab-action
"gj" 'fountain-outline-forward
"[" 'fountain-outline-previous
"gk" 'fountain-outline-backward
"SPC TAB" 'outline-hide-subtree)

(general-create-definer leader
  :prefix "SPC")

(leader
:states '(normal visual)
:keymaps 'fountain-mode-map
"w" 'widenToCenter
"n" 'org-narrow-to-subtree))
```

**Comment by mrbig033** [comment]
Okay, I'm an idiot. I mapped `TAB` to `fountain-tab-action` without specifying the keymap, so it went global. I even corrected the mistake before, but I lost the correction after reverting my init. I'm sorry for taking your time, closing the issue.

**Comment by rnkn** [comment]
No worries, thanks for the followup.
