### ISSUE TITLE
Missing 'h' from protocol.

### ISSUE THREAD

**Issue by rickysullivan** [rnkn/fountain-mode#107]
https://github.com/rnkn/fountain-mode/blob/72129c651c5f7537f17801e8d785880ed1ac8f43/docs/index.html#L252

**Comment by rickysullivan** [comment]
https://github.com/rnkn/fountain-mode/commit/8a20301555b9ee3681e0db5c362c5e228cbe7697#diff-eae600270579316beb8b8d9b9a5732d4R257

**Comment by rnkn** [comment]
Thanks kemosabe
