### ISSUE TITLE
Script notes breaking imenu lists

### ISSUE THREAD

**Issue by SimonGZ** [rnkn/fountain-mode#108]
After a recent update, imenu/imenu-list stopped working for me with the following message: 

    imenu-list: couldn’t create index because of error: (wrong-type-argument integer-or-marker-p nil)

I started fiddling with various projects and finally nailed down that the problem is script notes. Basically any script note (text between "[[" and "]]") breaks imenu. I presume this has something to do with a change to the regex or something else.

Thanks again for the continued awesome work and updates on fountain-mode.

**Comment by rnkn** [comment]
Thanks for this. Yep it was just a regexp group change.

**Comment by SimonGZ** [comment]
That fixed it! Thanks.
