### ISSUE TITLE
Wrong match-string index for evaluation of scene indexes.

### ISSUE THREAD

**Issue by smr894** [rnkn/fountain-mode#109]
Hello,

When adding scene numbers, the code halts with an error and only the first number is inserted (or none at all if at least one number was already present).

The error seems to be in function fountain-get-scene-number, where calls to (match-string 8) should be replaced by (match-string 9) as the 8th sub match refers to the first # of the scene number.

Regards,

(Version used: 2.7.3, on Emacs 26.3)

**Comment by rnkn** [comment]
Thanks for investigating/reporting this. Fixed in b21ba32cb54047d4f32a384876a0d3f5f91e111f
