### ISSUE TITLE
Export to txt (and html, latex) does not expand {{content}} and other variables

### ISSUE THREAD

**Issue by julitopower** [rnkn/fountain-mode#111]
Input file:
```
JULIO
What is this nonsense I hear about?
(looking at the window)
I thought I had made it clear this was not the way I wanted. Please change it immediately.

MATILDA
(Walking into the room)
Hey. What's that I've heard about things not working the way we want?
```
after executing ```M-x fountain-export-buffer-to-txt```, the generated file contains:

```
{{title-page}}{{content}}    
```

OS: Debian Stretch
Emacs: 2.5 (installed via apt-get)
Latex: TexLive
Fountain-mode: Melpa: 20191217.914

**Comment by rnkn** [comment]
Sorry but I can't reproduce this. I tried with the version available on MELPA too.
Have you tried with `emacs -Q`?

**Comment by rnkn** [comment]
Also what does `M-x version` say?

**Comment by julitopower** [comment]
```M-x version```: GNU Emacs 25.1.1 (x86_64-pc-linux-gnu, GTK+ Version 3.22.11) of 2017-09-15, modified by Debian

Starting emacs with the following I am able to generate a correct LaTeX export:

```
emacs julio.fountain -Q -l ~/.emacs.d/elpa/fountain-mode-20191217.914/fountain-mode-autoloads.el 
```
 My [emacs init.el file](https://github.com/julitopower/DockerLatexEmacs24Pandoc/blob/emacs25-pandoc2.9.1/emacs.d/init.el) has a lot of customization and clearly something is interfering with fountain.

Thanks for your help

**Comment by rnkn** [comment]
Without testing, nothing in your init looks terribly problematic. The only thing is maybe the function on `buffer-list-update-hook`, which might be better on `window-configuration-change-hook`.

**Comment by julitopower** [comment]
The offending expression is:

```
(setq-default case-fold-search nil)
```

After commenting it out, I am able to export correctly

**Comment by rnkn** [comment]
Thanks for the followup. I think you've found a bug, since fountain-mode is written making the bad assumption that `case-fold-search` is non-nil. I'll fix that soon.

**Comment by rnkn** [comment]
`case-fold-search` is now set (locally) in every fountain buffer.
