### ISSUE TITLE
Character name completion dupplicates

### ISSUE THREAD

**Issue by mrbig033** [rnkn/fountain-mode#116]
### My Environment

- **OS**: MX Linux 19
- **$ uname -r**: 4.19.0-6-amd64
- [dotfiles](https://github.com/mrbig033/dotfiles)
- **i3wm** version 4.16.1
- [~/.config/i3](https://github.com/mrbig033/dotfiles/blob/master/i3/config)
- **GNU Emacs** 26.3 (build 1, x86_64-pc-linux-gnu, X toolkit, Xaw3d scroll bars) of 2020-01-31
- [~/.emacs.d](https://github.com/mrbig033/emacs02)
- [init.org](https://github.com/mrbig033/emacs02/blob/master/init.org)
- [init.el](https://github.com/mrbig033/emacs02/blob/master/init.el)
- **Fountain version** 20200307.943
- [Fountain use-package](https://github.com/mrbig033/emacs02/blob/master/init.org#fountain-mode)

### Issue

Whenever a character has more than one line in a script, using `fountain-dwim` (via `TAB`) to complete it (after typing one or two letters) will render a bunch of identical completions.

So with this text:

```
DRIVER
You.

The unmoved face of Death.

DRIVER
Some people hate doing this. They think it's a sacrifice, and that I'm poor. Not me. I always wanted to be a bus driver, like the old man.

The unmoved face of Death.

DRIVER
I traveled with him sometimes. He let me drive, sat on his lap. The truck life is simple: just you and the road.
```

I get this:
![fountain_shot](https://user-images.githubusercontent.com/36245777/76211005-0e629180-61e4-11ea-9f4d-2223cf8c62a4.png)

Since they're identical, the completion should only display a single option.

**Comment by rnkn** [comment]
Please attempt to reproduce this with `emacs -Q` and `M-x load-file RET [PATH TO FILE]`

**Comment by mrbig033** [comment]
That works! I have no idea what might be cause this, though. The issue persists even if I remove all my fountain configurations.

**Comment by rnkn** [comment]
Looks like you're using `company`? How'd you get this to work with `fountain-mode`?

Apply this patch and let me know if it works:
~~~diff
diff --git a/fountain-mode.el b/fountain-mode.el
index 51192d3..53641eb 100644
--- a/fountain-mode.el
+++ b/fountain-mode.el
@@ -1165,17 +1165,13 @@ important."
           contd-character (car scene-characters)
           rest-characters (cddr scene-characters)
           scene-characters nil)
-    (when rest-characters
-      (setq scene-characters rest-characters))
-    (when contd-character
-      (setq scene-characters
-            (cons contd-character scene-characters)))
-    (when alt-character
-      (setq scene-characters
-            (cons alt-character scene-characters)))
-    (append scene-characters
-            fountain-completion-additional-characters
-            fountain--completion-characters)))
+    (when rest-characters (setq scene-characters rest-characters))
+    (when contd-character (push contd-character scene-characters))
+    (when alt-character (push alt-character scene-characters))
+    (delete-dups
+     (append scene-characters
+             fountain-completion-additional-characters
+             (mapcar 'car fountain--completion-characters)))))
 
 (defun fountain-completion-at-point ()
   "\\<fountain-mode-map>Return completion table for entity at point.
~~~

**Comment by mrbig033** [comment]
> Looks like you're using `company`? How'd you get this to work with `fountain-mode`?
> 
> Apply this patch and let me know if it works:
> 
> ```diff
> diff --git a/fountain-mode.el b/fountain-mode.el
> index 51192d3..53641eb 100644
> --- a/fountain-mode.el
> +++ b/fountain-mode.el
> @@ -1165,17 +1165,13 @@ important."
>            contd-character (car scene-characters)
>            rest-characters (cddr scene-characters)
>            scene-characters nil)
> -    (when rest-characters
> -      (setq scene-characters rest-characters))
> -    (when contd-character
> -      (setq scene-characters
> -            (cons contd-character scene-characters)))
> -    (when alt-character
> -      (setq scene-characters
> -            (cons alt-character scene-characters)))
> -    (append scene-characters
> -            fountain-completion-additional-characters
> -            fountain--completion-characters)))
> +    (when rest-characters (setq scene-characters rest-characters))
> +    (when contd-character (push contd-character scene-characters))
> +    (when alt-character (push alt-character scene-characters))
> +    (delete-dups
> +     (append scene-characters
> +             fountain-completion-additional-characters
> +             (mapcar 'car fountain--completion-characters)))))
>  
>  (defun fountain-completion-at-point ()
>    "\\<fountain-mode-map>Return completion table for entity at point.
> ```

Company is not enabled for Fountain Mode. But I'll try your solution and give feedback.

**Comment by rnkn** [comment]
What's giving you the dropdown completion candidates in your screenshot?

**Comment by mrbig033** [comment]
> What's giving you the dropdown completion candidates in your screenshot?

1. Type first letter(s) of character name
2. Hit `Tab`
