### ISSUE TITLE
How do I add a new profile to fountain export profiles

### ISSUE THREAD

**Issue by drjswalker** [rnkn/fountain-mode#135]
I am an elisp newbie and I've run into problems adding a profile to the fountain export profiles list.

I used this in my init.el

(add-to-list 'fountain-export-command-profiles
	     '("afterwriting-usletter-doublespace-draft" , "afterwriting \
              --source %b --pdf %B.pdf --overwrite \
              --setting double_space_between scenes=true
	       --setting print_profile=usletter
	       --setting print_watermark=\"DRAFT\"
	       --setting print_footer=%F"))

and when I try and use it, I get the following error message

fountain-export-command: Wrong type argument: stringp, ((\, "afterwriting               --source %b --pdf %B.pdf --overwrite               --setting double_space_between scenes=true
	       --setting print_profile=usletter
	       --setting print_watermark=\"DRAFT\"
	       --setting print_footer=%F")) 

I'm not sure where I am going wrong. Any help would be appreciated. I'm sure it's something simple.

P.S. How do I pass a config file in a profile?

**Comment by rnkn** [comment]
From the Emacs options UI.

In the menu click Fountain > Customize Mode, at the bottom of that buffer under **Subgroups** click Fountain Export. The option you want is `Fountain Export Command Profiles`.
