### ISSUE TITLE
File preview: How do I set C-c v to open my exported pdf with pdf-view mode in emacs

### ISSUE THREAD

**Issue by drjswalker** [rnkn/fountain-mode#136]
Hi

I'd like to be able to open the preview of my script in pdf-view mode in emacs (the fountain file is exported to a pdf by afterwriting via the export command) using the built in shortcuts . I can open the pdf file in emacs using C-x f (i have pdf-tools installed)  but I have to type the file name. When I try to use C-c v I get the error: "dired-guess-shell-alist-user not configured correctly".  My guess is that it defaults to shell commands to open the various file types it can export. How do I get it to use pdf-view mode for pdfs but retain the ability to use shell commands for the other file types?

**Comment by rnkn** [comment]
That command is only going to call shell commands. If you want C-c v to call a pdf-tools command you will need to rebind it.

**Comment by rnkn** [comment]
Several people have been confused by this command. It probably needs a rethink. Perhaps calling an export command should store the export filename in a local variable then attempt to open that file.

**Comment by rnkn** [comment]
The latest version will now export to PostScript/PDF and visit that exported file in a buffer.

**Comment by drjswalker** [comment]
That is a wonderful solution. Well done and thank you very much.

John Walker

P.S. sorry for.not replying to your earlier emails. I had CoVID and was
quite ill.

**Comment by rnkn** [comment]
That's awful. I'm sorry to hear that.

Please test out the latest version and let me know how it works for you :)
