### ISSUE TITLE
Can company-mode be integrated?

### ISSUE THREAD

**Issue by chariegg** [rnkn/fountain-mode#139]
This is a small request, but can we see to that company-mode backend is integrated with fountain mode? So it keeps tabs on character or keywords like INT. and show completion options for it.

**Comment by rnkn** [comment]
Company mode is already supported through the regular completion-at-point function. You just need to bind `company-complete` to something:

<img width="687" alt="Screenshot 2023-12-12 at 13 00 35" src="https://github.com/rnkn/fountain-mode/assets/1256849/044e01ea-57f5-4466-bb0e-c0161dcdeca0">
