### ISSUE TITLE
There should be a link to writersolo as an additional tool.

### ISSUE THREAD

**Issue by chariegg** [rnkn/fountain-mode#140]
[This](https://writersolo.com/) website, writersolo, absolutely should be in the README. It's not just a screenwriting tool, but also great for collaboration, very verbose analysis of the screenplay (Much more than what I've seen from VSCode), and most importantly: Conversion from fountain (It can import fountain among other formats) and export to PDF and even .cltx, .fadin, and even .fdx so you can absolutely ensure that you can work with a final draft user even if you're using emacs. I would say with this website (Which is the free version of WriterDuet), the need for included screenplay stats is significantly less of something that needs be implemented immediately. Especially when it can remove a lot of the heavy lifting from you. If you want to include screenplay stats later, that's cool still. I'm only saying this website is really useful to know and use.

**Comment by rnkn** [comment]
The linked tools are only those that can be used as CLI tools from within Emacs. The https://fountain.io website has links to more general purpose programs.
