### ISSUE TITLE
In case you have rewritten history by accident

### ISSUE THREAD

**Issue by tarsius** [rnkn/fountain-mode#146]
I've noticed that you have recently completely rewritten history. However, you did not rewrite tags, so I am guessing you might have done this by mistake. If you did do this on purpose, could you please to it again (after reverting pre-rewrite), making sure you also update the tags?

**Comment by rnkn** [comment]
Hi @tarsius,
Thanks for pointing this out. It was my misguided attempt to resolve my absurd .mailmap. But this is probably a sign I should not have. I've pushed the old history. If you get a moment could you check to see if that resolves the tag problem?

**Comment by tarsius** [comment]
> It was my misguided attempt to resolve my absurd .mailmap.

I had a look. So you've had many email addresses over the years. That's okay, nothing to be ashamed about. ;D

> If you get a moment could you check to see if that resolves the tag problem?

Everything looks fine again. Thanks!

**Comment by rnkn** [comment]
I’d be curious how to accomplish this successfully if you happen to know.

**Comment by tarsius** [comment]
I've only used `git filter-branch`, but the new tool is `git filter-repo`. It has an option specifically to "apply" the contents of `.mailmap`. But again, I would recommend against doing that.

**Comment by rnkn** [comment]
Okay I did this because yolo, but please let me know if it creates problems for you.

**Comment by rnkn** [comment]
Disculpas amigo for the trouble this has caused you!

Thing is I've double checked everything with fresh clones for GitHub and everything shows the tags pointing to the correct commits.

```
$ git show-ref --tags | tail -n1
89a91513a4ce904a918e87911cab4200049f0db0 refs/tags/v3.7.3

$ git show -s 89a91513a4ce904a918e87911cab4200049f0db0
tag v3.7.3
Tagger: Paul W. Rankin <rnkn@rnkn.xyz>
Date:   Fri Mar 29 12:29:37 2024 +1000

Version 3.7.3

- Add missing options to Save Options command

commit 195fa8670456855b592e76fb495d03cc621ad647
Author: Paul W. Rankin <rnkn@rnkn.xyz>
Date:   Fri Mar 29 12:29:37 2024 +1000

    Add Version 3.7.3 to NEWS.md

$ git show -s 195fa8670456855b592e76fb495d03cc621ad647
commit 195fa8670456855b592e76fb495d03cc621ad647
Author: Paul W. Rankin <rnkn@rnkn.xyz>
Date:   Fri Mar 29 12:29:37 2024 +1000

    Add Version 3.7.3 to NEWS.md
```

And 195fa8670456855b592e76fb495d03cc621ad647 on GitHub also shows the tag v3.7.3.

Are you sure you're working from a fresh clone?

This is very much a solo endeavour. I double checked the network graph beforehand and there were no current clones apart from Emacsmirror. I don't expect there to be other clones out there so pain should be minimal.

**Comment by tarsius** [comment]
Uh, yes, you're right the tags are were they are supposed to me. Sorry about that. I'll have to check my mirror tooling, there seems to be a bug related to the pulling of (updated) tags.

> This is very much a solo endeavour. I double checked the network graph beforehand and there were no current clones apart from Emacsmirror. I don't expect there to be other clones out there so pain should be minimal.

Understood. My contacting you was more about trying to make sure this wasn't done by accident (that really happens occasionally), than trying to make you reconsider. But then you *asked*... :grinning:

**Comment by rnkn** [comment]
All good! Yeah I think it may be that git will rebase a new history with just `git pull --rebase` but will not overwrite tags unless you `git pull --tags -f`.

**Comment by rnkn** [comment]
Can you please let me know when you get this solved? I want to rewrite history of another package that's in Emacsmirror. I'll reopen the issue.

**Comment by tarsius** [comment]
> Can you please let me know when you get this solved?

The "update one package" command's "accept the rewrite" variant, now also forces an update of the tags.

(As before history rewrites, which go beyond a certain threshold, are not accepted automatically, but when I come to the conclusion that the rewrite is intentional, then the command I use to accept it, no longer fails to accept the rewritten tags as well.)

**Comment by rnkn** [comment]
Awesome. Just letting you know I'm considering rewriting history of [olivetti](https://github.com/rnkn/olivetti) and [side-hustle](https://github.com/rnkn/side-hustle) but I'll wait to see if there are any more complaints here first.

**Comment by tarsius** [comment]
No more objects from me.

**Comment by tarsius** [comment]
I see you did some more rewrites and have updated the Emacsmirror accordingly.

The tags of `olivetti` still point at commits from before the rewrite. I used a fresh clone to confirm this.

The tags of the other repositories have been properly updated.

**Comment by rnkn** [comment]
Sorry about that. Should be fixed now. Thanks for your guidance on this.
