### ISSUE TITLE
fountain-pagination-update never finishes with a certain set of lines

### ISSUE THREAD

**Issue by cdmojoli** [rnkn/fountain-mode#150]
The following fragment, whose first line is empty, causes fountain-pagination-update to never exit.

```

ANY
Sueldos mínimos. Redondeando. *doscientos*.
```
Minimal changes in the dialogue line makes it work. Obviously hitting some corner case.

**Comment by rnkn** [comment]
Hi,

Thanks for reporting this. Looks like it's a problem with `fountain-goto-page-break-point` (which is unfortunately a rather large function). Leave it with me.

**Comment by rnkn** [comment]
Quite an edge case. It was because the break point fell on the punctuation. I think this is fixed with f3e821797beecc73cc16e81bfcbbe126581359ec which is on MELPA now. Let me know if you have any more
