### ISSUE TITLE
"In repository "fountain-mode", HEAD on default branch "master" has diverged from "origin/master""

### ISSUE THREAD

**Issue by tshiunghan** [rnkn/fountain-mode#151]
I got the following message while updating packages on Doom Emacs. Which option should I choose?

> In repository "fountain-mode", HEAD on default branch "master" has diverged from "origin/master"
> 
> 1) Abort
> 2) Merge "origin/master" into "master"
> 3) Rebase "master" onto "origin/master"
> 4) Reset "master" to "origin/master"
> 5) Magit log "master...origin/master" and open recursive edit
> 
> How to proceed? (1, 2, 3, 4, 5)

Not sure if this is a Doom Emacs issue or not, but let me know if this isn't appropriate and I'll delete the issue.

**Comment by rnkn** [comment]
Sorry it's because I rewrote the history. Choose 4, Reset.

**Comment by tshiunghan** [comment]
Thanks for the quick response!
