### ISSUE TITLE
Troff export generates an empty file

### ISSUE THREAD

**Issue by m4vnel** [rnkn/fountain-mode#153]
Hi, I've installed fountain in my emacs 29.3 in Linux Mint 22. When I try to export to .pdf, the minibuffer shows progress without errors ("Updating pagination", "Converting to troff... done") but the generated file is empty. I'm using the classical example "BigFish.fountain"

There's a buffer called "Fountain troff Output", but I know nothing about troff syntax. I attach it here.
[Fountain troff Output.txt](https://github.com/user-attachments/files/17777678/Fountain.troff.Output.txt)

**Comment by rnkn** [comment]
Hi, thanks for the bug report. The good news is that it's converting to Troff okay. Thanks for including that output, it's a big help.

It sounds like `groff` is not converting the troff output to PDF. I had a look around and found this on the Linux Mint community site:

> groff-base is a stripped-down package containing the necessary components to read manual pages in ASCII, Latin-1, and UTF-8, plus the PostScript device (groff's default). Users who want a full groff installation, with the standard set of devices, fonts, macros, and documentation, should install the groff package.

Two things to test. First change `fountain-export-format` to PostScript. That sounds like it should work with groff-base and give you a BigFish.ps file instead of a PDF.

To get PDF you might need to install the full groff package.

Let me know how you go.

**Comment by m4vnel** [comment]
My apologies. I should have checked the `groff` package. I've tested the two things and all is working right: with `fountain-export-format` set to Postscript, a nice .ps file is created, and after install the full groff package, a correct .pdf file.

I've realized, though, that in the two files (identical) the text it's a little too wide. I don't know if it's the groff conversion or what, so I attach one page from my .pdf and the similar text from the original version in the fountain.io site, in case you wanted to check this. Also, the original has 122 pages while the generated 115.
[Big Fish Page 6.pdf](https://github.com/user-attachments/files/17784409/Big.Fish.Page.6.pdf)
[Big Fish Page 6 orig.pdf](https://github.com/user-attachments/files/17784410/Big.Fish.Page.6.orig.pdf)

 
Anyway, thank you very much for the fast and kind answer and, of course, for this great package :-)

**Comment by rnkn** [comment]
Good, I'm glad.

Yeah I've spent a lot of time trying to match up pages from various sources. I try to match Final Draft output the closest, and the Nicholl Fellowship sample script (which don't match each other exactly either). It's unfortunately not an exact science.
