### ISSUE TITLE
Support for forced character names

### ISSUE THREAD

**Issue by 4of92000** [rnkn/fountain-mode#35]
According to [fountain.io](http://fountain.io/syntax#section-character), the character setting can be forced with the `@` character, like this:

```
THOMPSON
Mr. MacDuff wants to see you.

O'BREEN
Oh, he's in town?

MacDUFF walks through the door.

@MacDUFF
Hi, how nice to see you!
```

It'd be nice if you implemented that in the WYSIWYG.

Thanks.

**Comment by rnkn** [comment]
Hmm this should already work. Screenshot below...

![image](https://dl.dropboxusercontent.com/u/94472468/screenshots/Screen%20Shot%202015-04-27%20at%2011.48.58%20am.png)

Can you do me a favour? Can you try doing an `emacs -q` start, loading up `s.el` and `fountain-mode.el` and see what happens?

**Comment by 4of92000** [comment]
Now that I think about it, my copy of s.el may be broken, or worse, never installed.

However, `.` for forced scene headers still works.

I will get back to you once I get back to my copy of Emacs.

**Comment by 4of92000** [comment]
Okay, it works now.

?!

Sorry for wasting your time.

**Comment by rnkn** [comment]
No problem. I wouldn't dismiss there being some intermittent conflict with the `outline` code. If it happens again, can you try cycling the outline visibility with `S-TAB` and also changing the font-lock level with `C-c C-x f [1-3] RET`?

If either of those makes a difference I'll know there's a bug and where to find it.
