### ISSUE TITLE
Warning in Minibuffer on Every Insert

### ISSUE THREAD

**Issue by cdr255** [rnkn/fountain-mode#38]
Running Slackware Linux 14.1 and Emacs 24.3. Installed fountain-mode 1.5.0 from MELPA.

As soon as I enter the mode using M-x fountain-mode, every time a character is inserted into the buffer (typing text, pasting, etc) the following warning appears in the minibuffer:

    Warning: defvar ignored because font-lock-end is let-bound

Looking at \*Messages\*, the full sequence of errors seems to be:

    Warning: defvar ignored because font-lock-beg is let-bound                                                                                                                                                          
    Warning: defvar ignored because font-lock-end is let-bound 

I've tested it in emacs-24.3-no-x11 in an xterm (which I normally use), emacs-24.3-with-x11 as an X application, and on a true TTY... same warning. I tried using root, to see if it was a problem with my specific .emacs file / a conflict of packages I have installed... same warning. And finally, I created a new user on my system, with a completely clean .emacs and $HOME, set up MELPA, reinstalled, and then tried all three ways again... same warning. So, I am reasonably sure it isn't my emacs setup.

I am unfamiliar with both of those variables, and they don't seem to show up when I try to describe them (they are auto-corrected to *font-lock-beginning-of-syntax-function* and *font-lock-comment-end-skip*, respectively). I'm not very familiar with elisp or emacs packages (kind of a neophyte in that area, to be honest), so that could easily be the reason I don't know what the issue is.

Googling the issue didn't reveal anything useful on the first few tries, partly because this is usually not a repetitive warning: it usually shows up once, and either throws an exception or quiets down after (at least from what I have read). I'm not entirely sure what the long-ranging effects of the ignored defvar are, but if I could suppress the warning I might be able to work around them. As it stands, I can't really use the mode if I lose my minibuffer: it breaks my workflow.

Sorry if I am missing something obvious! I did a quick scan of both the open and closed issues here, and didn't see something similar to the problem I am having. I re-read the README, to see if there were more steps to be taken after installing from MELPA (aside from adding the file extension associations), and didn't see any listed.

I'm kind of at a loss at where to go from here. Any ideas?

**Comment by rnkn** [comment]
Sorry that you're having trouble, and thanks for the very thorough investigation. Unfortunately I can't reproduce this as I'm on Emacs 24.5. I think I've made some changes that require 24.4, which I see doesn't come with Slackware. Is it possible to upgrade to 24.4?

A quick fix that will hopefully get you back to writing (while I investigate further) is to comment out these lines and restart: https://github.com/rnkn/fountain-mode/blob/master/fountain-mode.el#L2888-2889

However, I think there are other things that require 24.4, it might be a multi-step process to get things working on 24.3 (but not impossible!).

As an aside, `font-lock-beg` and `font-lock-end` are variables only used for extending the region for Font Lock (see `font-lock-extend-region-functions`).

Let me know how you go.

**Comment by cdr255** [comment]
Hey, thanks for the speedy response!

I decided to upgrade my system to -current, which actually has emacs 24.5 by default. As soon as that upgrade was finished, the warnings disappeared.

`font-lock-extend-region-functions` was the term I was missing. I understand those variables now, very straightforward.

Thanks for the quick help and support! Looking forward to using `fountain-mode` now!

**Comment by rnkn** [comment]
Awesome. Glad to hear it. Any suggestions for improvement be sure to pass them on, and good luck writing!
