### ISSUE TITLE
Error while loading fountain-mode: called with 3 args, but requires 2

### ISSUE THREAD

**Issue by cweiske** [rnkn/fountain-mode#39]
I installed `fountain-mode 20150618.116`  in `emacs 24.3.1` from melpa, and immediately after installation got the following warnings:

```
Compiling file /.../.emacs.d/elpa/fountain-mode-20150618.116/fountain-mode.el at Thu Dec  3 21:44:15 2015

In fountain-outline-cycle:
fountain-mode.el:1746:15:Warning: `<' called with 3 args, but requires 2
fountain-mode.el:1785:31:Warning: < called with 3 arguments, but accepts only
    2

In fountain-set-font-lock-decoration:
fountain-mode.el:2460:13:Warning: `<=' called with 3 args, but requires 2
fountain-mode.el:2460:13:Warning: <= called with 3 arguments, but accepts only
    2
```

**Comment by rnkn** [comment]
You need Emacs 24.4.

**Comment by rnkn** [comment]
I've added 24.4 to the package requirements to prevent these kinds of errors in the future. https://github.com/rnkn/fountain-mode/commit/934243afbfa042643a973af1b6f26d7353517526

If you're unable to install 24.4 you can change those lines of code to be backwards compatible by reversing what you see here: http://emacsredux.com/blog/2014/03/22/a-peek-at-emacs-24-dot-4-variadic-comparison-functions/
