### ISSUE TITLE
Allow tabs when indenting title page values

### ISSUE THREAD

**Issue by dunn** [rnkn/fountain-mode#45]
According to the spec, [multiline values on the title page can be indented with tabs](http://fountain.io/syntax#section-titlepage), but currently fountain-mode doesn't parse them correctly (using this test file: https://gist.github.com/anonymous/334a634d774a994b9266).

Mac OS 10.11.3, Emacs 25.0.91, commit 45db55aa6c79d2461a45fe21e5da56e8c8c10a1d

**Comment by rnkn** [comment]
Should be fixed with the latest push. Output of test.html: https://rawgit.com/rnkn/236e30d6c75ed4f5d9b6/raw/9f2e4deb476fe0b3ba2bb914d63620dab2bccc8b/test.html

**Comment by dunn** [comment]
Awesome, thanks!
