### ISSUE TITLE
Variable for LaTeX' local variables

### ISSUE THREAD

**Issue by tty-tourist** [rnkn/fountain-mode#52]
To successfully compile the exported LaTeX buffer to pdf, I've added these local variables to the bottom of fountain-export-templates:

```
%%% Local Variables:
%%% mode: latex
%%% TeX-engine: luatex
%%% End:
```

(Not sure if this is a sensible way to change the engine, only just learning LaTeX now).

Anyways, customizing fountain-export-templates adds a really big chunk of code to one's custom-file, so maybe it would make sense have a dedicated variable for  `%%% Local Variables:` that will be appended to the LaTeX template.

**Comment by rnkn** [comment]
The included TeX template is really just for XeTeX. I'll make sure to add the `TeX-engine: xetex` local variable. I'm pretty sure XeTeX comes with a default TeXLive installation whereas LuaTeX doesn't.

This should alleviate the need for a `fountain-export-tex-local-vars`. I want to minimize the use of these as the idea is the exporter is format agnostic, allowing anyone to add any new format they like. However you could add this yourself, e.g. customize `fountain-additional-template-replace-functions` and add...
```elisp
("tex-local-vars" (lambda ()
"%%% Local Variables:
%%% mode: latex
%%% TeX-engine: luatex
%%% End:"))
```
Then you can use `${tex-local-vars}` in any template.

I'll keep this open until I add the local variables to the default template.

**Comment by rnkn** [comment]
Please disregard instruction for using `fountain-additional-template-replace-functions` as I've removed this (it didn't work very well).

The default LaTeX template now sets
~~~tex
% Local Variables:
% TeX-engine: xetex
% End:
~~~
which should resolve the problem.
