### ISSUE TITLE
Export to PostScript

### ISSUE THREAD

**Issue by Spass1966** [rnkn/fountain-mode#70]
LaTeX is awful and requires a huge number of dependencies for printing to PDF. consider adding an option to export to PDF via PostScript
 https://emacs.stackexchange.com/questions/9364/convert-a-text-buffer-to-a-pdf-file

**Comment by rnkn** [comment]
Already in progress in [v3.0](https://github.com/rnkn/fountain-mode/milestone/8)

**Comment by rnkn** [comment]
In the meantime you'll get better PDF output by using [afterwriting](https://github.com/ifrost/afterwriting-labs/blob/master/docs/clients.md) and `C-c C-e s`.

**Comment by rnkn** [comment]
Closing this as I’ve removed to export code from fountain-mode — the external tools available do a far better, faster and easier job of converting a fountain file to various formats.
