### ISSUE TITLE
How do I avoid indenting action?

### ISSUE THREAD

**Issue by raymestalez** [rnkn/fountain-mode#71]
Hi! I'm new to fountain-mode. Every time I'm pressing RET to move to the new line(while writing action), it automatically indents it with a few spaces. Can you help me to disable this? I need RET to create a new line and put the cursor at the beginning.

I've tried doing 
```
M-x set-variable 
left-margin 0
```
But that doesn't work.

**Comment by rnkn** [comment]
Hmm not sure what this is as I've not experienced it. Can you try starting Emacs with `emacs -Q` then load `fountain-mode.el` and see if it still happens?

You can load files with `M-x load-file RET [path] RET`.

**Comment by raymestalez** [comment]
Okay, so after a bit of experimenting I've found out that if I add:

```
(set-variable 'electric-indent-mode nil)
```
to `.emacs`, RET begins working properly, so when I press Enter, cursor moves to the beginning of the new line.

But I still can't use `C-j`, to automatically move to the new line and indent, so if I press it after the CHARACTER'S NAME to start writing the dialogue, it adds extra several spaces(on top of the dialogue indentation). It seems like there's some sort of a variable set that makes it indent extra few spaces...

**Comment by raymestalez** [comment]
Huh, interesting, launching emacs with -Q and loading fountain-mode separately works, everything seems to work as it supposed to!

Thank you very much for your advice, it seems like I could've messed up something in my config, though I don't know what...

**Comment by rnkn** [comment]
Sounds like there's something in your init that's setting an indent for text-mode derived modes.

But you shouldn't need C-j as there's no indentation for character/dialogue in Fountain. What you see in the screenshot is a display-only text alignment and doesn't affect the file contents. You can toggle this in the menu to get an idea.

**Comment by raymestalez** [comment]
Awesome, thank you so much for your help! I've cleaned up my `.emacs`, and now everything works well!
