### ISSUE TITLE
[wishlist] please document how to use olivetti window + imenu outline window

### ISSUE THREAD

**Issue by sten0** [rnkn/fountain-mode#72]
Followup for: rnkn/olivetti#18

Please document how to use olivetti window + imenu outline window. :-)

Thank you,
Nicholas

**Comment by rnkn** [comment]
Sorry I’m not sure what you mean? They each have their own documentation. Or are you having trouble making them work with fountain mode?

**Comment by sten0** [comment]
Maybe add olivetti and imenu-list to either the Requirements or a "Recommended extensions" section of README.md?

**Comment by rnkn** [comment]
Ah ha, it’s in the wiki: https://github.com/rnkn/fountain-mode/wiki/Tips-and-Tricks#use-olivetti
Feel free to add imenu-list and anything else you like... if you’re feeling particularly ambitious you could do a page about the Debian package when it’s ready 😎
