### ISSUE TITLE
Page count don't like long monologues

### ISSUE THREAD

**Issue by johnnygroovy** [rnkn/fountain-mode#82]
Well very long monologues, so nothing really problematic.

But if you write something like [this](https://pastebin.com/uMswgELX) (I wish I could), C-c C-x p will freeze emacs and cpu go to 100%.

**Comment by rnkn** [comment]
Thanks for the report. You appear to have discovered an infinite loop, i.e. `(fountain-forward-page)` gets stuck at "So three days before..."

**Comment by rnkn** [comment]
Fixed in master. Will be included in next stable release.
