### ISSUE TITLE
Hash symbol exported incorrectly to LaTeX

### ISSUE THREAD

**Issue by vedranmiletic** [rnkn/fountain-mode#83]
If the dialogue contains `#`, it will be exported to LaTeX as `#` instead of `\#` and the compilation with fail.

**Comment by rnkn** [comment]
The LaTeX export is a pretty poor way to create a PDF, and will be removed soon. Instead I'd recommend [afterwriting CLI](https://github.com/ifrost/afterwriting-labs/blob/master/docs/clients.md).

**Comment by vedranmiletic** [comment]
Please keep it. Over here we're a group of ~20 scientists doing amateur theatre and literally everybody has LaTeX installed in one form or another (recent TeX Live is the most common, so `xelatex` and `lualatex` are there). Node is another completely different ecosystem which in turn raises the bar to acceptance.

I'm not an expert on Lisp, but I guess it can't be too hard to do one string replacement, so if it would take a patch submission to keep LaTeX working, I'm willing to look into it.

**Comment by rnkn** [comment]
Should be fixed now. The LaTeX export would only be replaced by a native Emacs export via PostScript (i.e. no external dependencies). But presently, afterwriting is the best way to get a PDF.

**Comment by vedranmiletic** [comment]
It indeed works, thank you!

I would suggest to keep LaTeX export and just add another option (`Export to PDF`), this one is `Export to LaTeX` after all so there's no conflict between the two. At least from our perspective, it works perfectly the way it does (and I understand that others see it differently, i.e. the reporter from #70 obviously doesn't use TeX regularly).

**Comment by rnkn** [comment]
Hmm, if you could reliably export a PDF without using LaTeX, why do you then also want to export a PDF using LaTeX?

**Comment by vedranmiletic** [comment]
Personally, I like the way TeX (including XeTeX/LuaTeX) does typography (everything from [LaTeX default style math course lecture notes](http://www.math.ucsd.edu/~bdriver/240A-C-03-04/240_lecture_notes.htm) to [this particular showcase of beautiful typography](https://tex.stackexchange.com/questions/1319/showcase-of-beautiful-typography-done-in-tex-friends). (I will admit that I am somewhat biased here, being a fan of Donald Knuth's work in general and TeX in particular, I used to develop/maintain LaTeX Beamer some years ago to make it work for my teaching materials, and back in the day I also promoted TeX Live in our CS and BioTech departments; in Math and Phy everybody was using it by default.)
