### ISSUE TITLE
Export missing transition "CUT TO:"

### ISSUE THREAD

**Issue by balaramadurai** [rnkn/fountain-mode#92]
Hello,
  Thank you for such a wonderful software! I find it extremely useful and easy to use in the default states.

One niggle for me is that "CUT TO:" transition doesn't export to html, txt and tex formats. I haven't tested with other formats or transitions.

Thank you again for your work on this one.
Bala

**Comment by rnkn** [comment]
Thanks for reporting this. It's a recent bug in the master/unstable version, but if you switch to the MELPA-stable version it's okay.
