### ISSUE TITLE
noticeable lag while typing

### ISSUE THREAD

**Issue by ctholho** [rnkn/fountain-mode#93]
Hey,
when I type in fountain mode there is a noticeable lag between each keystroke and sometimes it seems that a whole (although mostly short words) only appear after I typed them.

So I experimented a little and could exclude that it's not entirely emacs (spacemacs) because a fully enabled python layer with pyflakes doesn't have the lag.

After reboot the lag is gone until I start messing around with other buffers, org-mode and a 2 window follow-mode setup. Again: Under those conditions any other mode works faster.

Fountain-mode is still workable. And I love it. But if there is a switch that disables some features to make it faster I would like a more responsive touch-typing experience in exchange.

**Comment by rnkn** [comment]
Try start emacs with `emacs -Q` then `M-x load-file RET [path to fountain-mode.el] RET` and let me know if you can still reproduce the issue.

**Comment by ctholho** [comment]
Sorry for the delay.
Running vanilla emacs with fountain mode could not replicate the issue. So the problem is somewhere together with spacemacs. For now I use fountain mode without spacemacs.
