### ISSUE TITLE
Can't export to any format, error message: `fountain-export-element: Symbol’s value as variable is void: fountain-template-key-regexp`

### ISSUE THREAD

**Issue by mrbig033** [rnkn/fountain-mode#97]
+ GNU Emacs 27.0.50 (build 1, x86_64-pc-linux-gnu, GTK+ Version 2.24.31) of 2018-08-16
+ [init.el](https://gitlab.com/mrbig/emacs/blob/master/init.el)

I installed with use-package:

```
(use-package fountain-mode
:ensure t)
```

**Comment by rnkn** [comment]
Sorry about that. Should now be fixed in master. Let me know how you go and I'll tag another release.

**Comment by mrbig033** [comment]
Okay... when you say master, do you say I should install directly from this repository? Cause I just updated all my packages and there was no change.

**Comment by rnkn** [comment]
MELPA takes a little while before they rebuild packages.

I assume `use-package` pulls from MELPA not MELPA-stable.

**Comment by mrbig033** [comment]
Yeah.... my init is configured for MELP, not stable. I'm not in the mood to pull from git right now... I'll just wait for a bit, then.

Will report if there's a change. Thanks.
