### ISSUE TITLE
screenshot buffer on right

### ISSUE THREAD

**Issue by donsfan** [rnkn/fountain-mode#98]
Not so much an issue more a simple question. What is the buffer on the right in the screenshot? Looks very interesting/useful (notes?) but I can't figure out what it is.

**Comment by rnkn** [comment]
It was a feature that I have since separated into its own library: https://github.com/rnkn/side-notes

**Comment by donsfan** [comment]
Thanks for replying to so promptly that's a really interesting feature!

**Comment by rnkn** [comment]
I should really update the screenshot. Thanks for reminding me!
